---
title: "Notes for our BIP"
format: html
---

[*Learning outcomes set as knowledge and skills:*]{style="color:green;"}

1. Cadets will demonstrate the ability to apply training principles in the development of structured training programs that promote progressive improvement in physical fitness and military skills, with a particular emphasis on strength, power, and endurance as fundamental capacities for military pentathlon and operational demands.

1. Cadets will apply theoretical knowledge to design and implement both general and specific warm-up protocols, including those tailored to specialized exercises such as the grenade throw.

1. Cadets will develop a comprehensive understanding of how training plans and goal-setting contribute to human performance enhancement and overall operational readiness


[*OUT of class, virtual*]{style="color:green;"}

Learning activities:  
1. Lecture (10 min) about injury prevention and warm up as a strategy   
    -  assignment could be - general and specific part
    
2. Lecture (10 min) about training principles and training plan  
    -  assignment could be: a training plan that should be presented during the workshop
          + progression, specificity, variation, periodization, leading to skeletal muscle adaptations (load).


[*IN class lectures:*]{style="color:green;"}

Active learning part 1:
- Student will with the virtual component and in class prepare for doing warm up session with the goal of injury prevention strategy (general + specific)

- Student warm up sessions: 4 classes / sessions of 30 min

Active learning part 2:
- Elaborate on a training program to improve military performance using the link between working demands - strength, endurance, train as you will fight.
- technique training

Active learning part 3: 
- here the cadets should present their training programs with some arguments for why this approach is beneficial for military performance / skills


[Schedule for physical component:]{style="color:green;"}

*Saturday*

Theory: injury prevention strategies

- **1.** How - cadets supervised session - activating the cadets to achieve greater learning outcome?

- Prep: general warm up for whole body and specific to a military skill...?

Physical session that day: individual basic technique - what is that excactly?


*Sunday*

Theory: military work demands and military pentathlon - the link

- **2.** How - cadets supervised session - activating the cadets to achieve greater learning outcome?
 
-  Physical session that day: grenade throw technique - we need elastics bands


*Monday*

Theory: i.a

- **3.** How - cadets supervised session - activating the cadets to achieve greater learning outcome?
 
- Physical session that day: its all about the team


*Tuesday*

Theory: Work shop

- **4.** How - cadets supervised session - activating the cadets to achieve greater learning outcome?

Physical: precision and length throw

*Wedensday*

Theory: optimizing physical performance

Physical: swimminghall (warm up by Trond?)

*Thursday*

Theory: 





