---
title: "Notes-Poster"
format: html
---


**Intro** 

So, with this project we aim to improve the learning outcome in military skills during a comprehensive educational week with focus on getting cadets **actively engaged** in their own learning process. Because, research shows that active participation leads to deeper learning, more reflection, and enhances students learning outcomes..


So, during this week they will DIG into military skills and working demands that they may face at operational battlefields.
Several of these demands connect directly to the five disciplines of the military pentathlon- which tests endurance, strength, coordination, and other key abilities essential for soldiers.


By combining theory and practice, the goal is to help cadets see how knowledge can directly improve their skills and performance.


The aim is that they should work actively with the theory and practical sessions, to better bridge the gap between theory and practice... To better see how they can use the theoretical knowledge to improve their military skills and performance....

So how, do we set up such a learning environment


**Project**
- In this project I used the Blended Intensive exchange program which is an appropriate framework to focus on active cadet learning process..

- In this project we have 16 international cadets together with 7 Norwegian cadets

- These cadets represents 7 different academies across Europe, all coming together here in Norway.

**Method**

- To achieve the aim, I uses the flipped class room approach, well suited to the blended format, as it consist of a virtual and physical component..

- So out of class, the cadets had mandatory video lecture, reading material and group assignment. This learning material was made available at the learning platform we had developed. 
So, on this platform, they had all material to acquire theoretical knowledge about military skills and the connection to the military pentathlon. Then, their task was to apply this theory to design a warm-up program related to military pentathlon skills.

- Then in class, when they arrive at our camp, they get a short recaplecture of the key points from the video lecture, before they have 10 minutes to present their warm-up program.. this presentation is discussed and reflected upon in light of the acquired theory by all cadets....

- Then out of class room, the last part is that they execute their warm-up program on the other cadets to prepare them for the upcoming military pentathlon training... 

So, this part was set up like a seminar, connecting the theoretical knowledge into immediate practice sessions. Hence, making the cadet active as they are responsible for both part of the lecture in class and the practical session, out of class.. 

**The final** part of the learning strategy was to making the cadets actively engaged through discussion and reflections using a WORKSHOP as a tool. The workshop is led by me that facilites the cadets to work in groups and discuss and reflect upon on their own work demands in their own specific field.. both in and out of class..  


**Outcome**

So to sum up, the virtual to physical component of the blended program using the flipped class room approach, we facilitated cadets to be more active in their own learning process to enhance their learning outcome in military skills..

Whether we suceed or not it yet to be evaluated during the upcoming week, as we tomorrow it putting this MSoTL-progject into real life..

Thank you