---
title: "warmup-notes to presentations"
format: html
---

### Overall impression_

### Specific



## Bulgaria

### Overall impression

Overall impression that you have used the background theory from the video lecture in preparing your program, and also spend some time reflecting on the program and exercises you have implemented to prepare the soldier for the following exercise, obstacle course...


### Specific
 Three overall physiologocal aspects is mentioned - givining me the impression that you have digged a little bit into the theoretical background..
 
- Mechanisms: 
    - Increased power output, as the rate of force development improves as the cross-bridge in cycling become more efficient...

- Nervous system through coordination between synergist and agonists/antagonist....


Question: what needs to be coordinated? 
- Temerature and circulation? why?: energy system speeds up and the muscles can generate energy faster and more effectively.. cross briding.. 
    - Important for performance and injury prevention purposes..



To consider for next time:
- Getting some progression in intensity towards the end of warm-up to take advantage of the elevated cardiorespiratory system and hence sparing the anaerobic system for the real competition (performance) can be implemented


Overall great set up..


--------

##  Greece

### Overall impression:

- How can warm-up reduce the risk of injuries...? Can you tell med this...

- Easy to follow with general to more specific muscle activation... 



### Specific

- Why is torso mobilization so of importance for the throwing movement? 
    - Injury? Performance?
    - Reduce stress on the shoulder joint and anterior stress..
    
- Muscle activation: anterior / posterior shoulder muscles?
    - Late phase de-accelration phase - so in a training program it should be at least 60% of the internal rotation strength to reduce risk of getting injured....
    
    
- Could it be included the whole kinetic-chain? for more specific warm up....    

- In this turn; include in- run for even more specific for the following event?     



-----

## Slovakia

### Overall impression_

Easy to follow you presentation. Theoretical background - nice summarizing key purposes for each step in the RAMP-method...




### Specific


I got the general to specific warm-up, but a little more detailed would be an advantage to consider the volume and intensity of the exercises you uses......

- Could you elaborate a little more into intensity they should be performing at?

- Even more like - sprints in the water or dry land?



-----


## Romania

